name: build

on:
  push:
    branches:
      - master
      - dev

env:
  GO111MODULE: "on"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Linters
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.40

  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.17

      - name: Check out code
        uses: actions/checkout@v2

      - name: tests
        run: make tests

  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.17

      - name: Check out code
        uses: actions/checkout@v2

      - name: tests
        run: go test -v -coverpkg=./... -coverprofile=coverage.txt -covermode=atomic -timeout=10m ./...

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.17

      - name: Check out code
        uses: actions/checkout@v2

      - name: build
        run: make build
