name: Minipic tests

on:
  push:
    branches:
      - master
      - dev

env:
  GO111MODULE: "on"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Linters
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.40